name: Test

on:
  push:
    branches: main
  pull_request: ~

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run GrumPHP
        run: vendor/bin/grumphp run
